### ISSUE TITLE
The vedio stream can't show rightly

### ISSUE THREAD

**Issue by adfghzhang** [vuquangtrong/androidmirrroing#1]
I run scrcpy and start mirror. When I open the broswer the cavans show me a borken image like the attch file. But I can control the device rightly. Please fix it.
![wechatimg14](https://user-images.githubusercontent.com/20984179/49725444-a6529200-fca6-11e8-8cd7-a7f67cddbcce.jpeg)

**Comment by vuquangtrong** [comment]
Hi, the project is at very beginning stage, so I just fixed the size of a frame.
please edit the `width` and `height` in file [mirror.js](https://github.com/vuquangtrong/androidmirrroing/blob/master/mirroring/mirror.js)
```
ws.send(JSON.stringify({
      action: 'init',
      width: '720',
      height: '1280'
    }));
```
and in [index.html](https://github.com/vuquangtrong/androidmirrroing/blob/master/mirroring/public/index.html)
```
wsavc.swipe(
            startX * 720 / width,
            startY * 1280 / height, 
            endX * 720 / width, 
            endY * 1280 / height,
            elapsedTime);
```
Please try and send me your feedback. I will update the code to send the frame size to client soon.

**Comment by adfghzhang** [comment]
yes, I change the size with my phone. But it still not work. Can you email to me and give me some help. My emil-addr:adfghzhang@live.cn

**Comment by vuquangtrong** [comment]
What is your phone model and its android version? `scrcpy` requires android 5.0+ (my old one is 4.3 and scrcpy doesnot work with it)

Could you add console.log() in the `http-live-player.js` at line 4446?
```
this.ws.onmessage = (evt) => {
      if(typeof evt.data == "string")
        return this.cmd(JSON.parse(evt.data));

      this.pktnum++;
      var frame = new Uint8Array(evt.data);
      console.log("[Pkt " + this.pktnum + " (" + evt.data.byteLength + " bytes)]");
      console.log(frame);
      //this.decode(frame);
      framesList.push(frame);
    };
```
Then in browser console, check the frame data which should be start with [0,0,0,1].
One more, please check the port 8091. it maybe blocked.

I have tested with Samsung S7 ( set at 720x1280, 1080x1920, 1440x2560)  and Nexus 6P (1440x2560).

**Comment by powerProgrammerMa** [comment]
![image](https://user-images.githubusercontent.com/32127058/49776055-81593000-fd35-11e8-96d6-2749fe8f3a4c.png)

![image](https://user-images.githubusercontent.com/32127058/49776086-a5b50c80-fd35-11e8-83d0-14c75ebcbf0c.png)


![image](https://user-images.githubusercontent.com/32127058/49776144-d006ca00-fd35-11e8-9d2b-17f72011a39a.png)
![Uploading image.png…]()

**Comment by powerProgrammerMa** [comment]
![image](https://user-images.githubusercontent.com/32127058/49776303-6dfa9480-fd36-11e8-9e54-cfad178866ff.png)

**Comment by powerProgrammerMa** [comment]
This mistake occasionally occurs.

**Comment by adfghzhang** [comment]
My Phone is Honor 7i with Android version 6.0 (1080x1920), RedMe Note4x with Android 6.0 (1080x1920)
powerProgrammerMa is my partner

**Comment by vuquangtrong** [comment]
It seems that the problem comes from [Broadway.js](https://github.com/mbebenita/Broadway) which cannot render portrait mode (1080x1920) but can render landscape mode (1920x1080).
![image](https://user-images.githubusercontent.com/843536/49778801-88823d00-fd39-11e8-870d-a7343678ec60.png)

I will check more and if problem is in Broadway.js, we should talk to him.

**Comment by adfghzhang** [comment]
I test on a genymotion emulator with landscape mode (1280x720), it works right. And I changed it to 720x1280 also work well.

**Comment by vuquangtrong** [comment]
You should test with Broadway.js or h264-live-player.js on browser. Genymobile's scrcpy emulator does not use JS rendering.

As I tested on browser, only portrait at size of 1080x1920 is not working.
Could you make a test with ffmpeg to stream 1080x1920 h264 to a web page? if it also fails, then the problem is from Broadway.js.

**Comment by wzrf** [comment]
Hi guys, did you figure it out? I'm using 1080 x 1920 device, and it's also not decoding properly.

**Comment by Snotra-p** [comment]
how can i decode correctly 2220x1080 ? plz help me

**Comment by krishtoautomate** [comment]
same issue

**Comment by wj2008** [comment]
which android version can't decode ?  是不是这个原因  “因为 Broadway 插件不支持 H264 baseline”

**Comment by MilkFlavor** [comment]
> You should test with Broadway.js or h264-live-player.js on browser. Genymobile's scrcpy emulator does not use JS rendering.
> 
> As I tested on browser, only portrait at size of 1080x1920 is not working. Could you make a test with ffmpeg to stream 1080x1920 h264 to a web page? if it also fails, then the problem is from Broadway.js.

This worked!

**Comment by MenuuTUX** [comment]
I think I got it. According to the original author of this project, this is a problem with Broadway.js. Apparently, it can only run in landscape mode. So I created a fork fixing these issues, however, the project still doesn't have rotation support. Here is the link: https://github.com/MilkFlavor/androidmirrroing

I'm gonna try adding rotation support, but for now, it only works on landscape mode. One of my solutions is to reduce the resolution of the images or the phone itself.

**Comment by airhandsome** [comment]
> I think I got it. According to the original author of this project, this is a problem with Broadway.js. Apparently, it can only run in landscape mode. So I created a fork fixing these issues, however, the project still doesn't have rotation support. Here is the link: https://github.com/MilkFlavor/androidmirrroing
> 
> I'm gonna try adding rotation support, but for now, it only works on landscape mode. One of my solutions is to reduce the resolution of the images or the phone itself.

Hello, I downloaded your project and tried to run it. However nothing is shown in to web. Can you help? My Email Address is: hansen_tear@hotmail.com

**Comment by MenuuTUX** [comment]
Did you run it with both scripts? You have to run it with `scrcpy.bat`, then go into the mirroring folder and run `npm run start`. I find this process kind of tedious so I'll try simplifying it to one command and completely getting rid of the `.bat` files at a later date. For the time being, you have to give more information about your situation. Also, feel free to create an issue or pull a request on my project.

**Comment by MenuuTUX** [comment]
I think of manually starting the adb server by running `scrcpy.bat` it'll be more efficient if we replace that with [appium-adb](https://www.npmjs.com/package/appium-adb) 
I'm also thinking of compiling the project to web assembly. Apparently, "Wasm is 1.15-1.67 times faster than JavaScript on Google Chrome on a desktop", it shouldn't be that difficult.
